### ISSUE TITLE
WebSphere Liberty Dockerfile

### ISSUE THREAD

**Issue by davidcurrie** [apexits/dockerimages#1]
It has come to my attention that your WebSphere Liberty [Dockerfile](https://github.com/apexits/dockerimages/blob/master/ubuntu-was-liberty-8.5.5-ibm-jdk8/Dockerfile) is based on our [Dockerfile](https://github.com/WASdev/ci.docker/blob/3e87d342469e4849a61a689f05ab4fe92af13ecf/websphere-liberty/8.5.5/developer/kernel/Dockerfile). IBM first wrote that code and licensed it under the Apache 2.0 license and, while I am sure it was inadvertent, it appears that you have deleted the IBM copyright notice as well as the Apache license notice.  We would appreciate it if you reposted the original code with the original notices.

Regards
David

**Comment by johndondapati** [comment]
Done. Thanks!

**Comment by davidcurrie** [comment]
John - many thanks for updating this so promptly. As you have made modifications to the file (which you are perfectly entitled to do under the license) please can you include a comment to that effect. (See section 4b of [the license](http://www.apache.org/licenses/LICENSE-2.0).)

Regards
David

**Comment by johndondapati** [comment]
Done. My apologies for missing the notice and the copyright. And thank you for being supportive.

**Comment by davidcurrie** [comment]
You're welcome - obviously we're more than happy for people to reuse these assets if it encourages uptake of WebSphere Liberty!
